repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.pb.*'
      - id: end-of-file-fixer
        exclude: '.*\.pb.*'
      - id: check-yaml
        exclude: '.*\.pb.*'
      - id: check-added-large-files
        exclude: '.*\.pb.*'

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
        exclude: '.*\.pb.*'
      - id: go-imports
        exclude: '.*\.pb.*'
      - id: no-go-testing
        exclude: '.*\.pb.*'
      - id: go-unit-tests
        exclude: '.*\.pb.*'
