# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/outbox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12proto/outbox.proto"\xb4\x02\n\x0bOutboxEvent\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12%\n\x0e\x61ggregate_type\x18\x02 \x01(\tR\raggregateType\x12!\n\x0c\x61ggregate_id\x18\x03 \x01(\tR\x0b\x61ggregateId\x12\x1d\n\nevent_type\x18\x04 \x01(\tR\teventType\x12\x18\n\x07payload\x18\x05 \x01(\x0cR\x07payload\x12\x1d\n\ncreated_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x36\n\x08metadata\x18\x07 \x03(\x0b\x32\x1a.OutboxEvent.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.outbox_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:

    DESCRIPTOR._options = None
    _OUTBOXEVENT_METADATAENTRY._options = None
    _OUTBOXEVENT_METADATAENTRY._serialized_options = b"8\001"
    _globals["_OUTBOXEVENT"]._serialized_start = 23
    _globals["_OUTBOXEVENT"]._serialized_end = 331
    _globals["_OUTBOXEVENT_METADATAENTRY"]._serialized_start = 272
    _globals["_OUTBOXEVENT_METADATAENTRY"]._serialized_end = 331
# @@protoc_insertion_point(module_scope)
